name: Benchmarks

on:
  push:
    branches: [ 'dev', 'master' ]
  workflow_dispatch:

jobs:
  benchmark:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 16
      matrix:
        node-version: [22.x]
        attempt: [1,2,3,4]
        ai:
          - openai:gpt-4o-mini
          - openai:gpt-4o
          - openai:o3-mini
          - google:gemini-1.5-pro
          - google:gemini-1.5-flash
          - google:gemini-2.0-flash
          - groq:llama-3.2-11b-vision-preview
          - groq:llama-3.2-90b-vision-preview
          - openrouter:openai/o3-mini
          - openrouter:meta-llama/llama-3.2-1b-instruct
          - openrouter:meta-llama/llama-3.3-70b-instruct
          - openrouter:google/gemini-flash-1.5-8b
          - openrouter:google/gemini-flash-1.5
          - openrouter:google/gemini-pro-1.5
          - openrouter:google/gemini-2.0-flash-001
          - openrouter:deepseek/deepseek-r1
          - openrouter:deepseek/deepseek-chat
          - openrouter:deepseek/deepseek-r1-distill-llama-70b
          - openrouter:anthropic/claude-3.5-haiku
          - openrouter:anthropic/claude-3.5-sonnet

    steps:
    - uses: actions/checkout@v4

    - name: Extract branch name
      id: get_branch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm run build --if-present


    - name: Run benchmarks
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
        CDP_URL: ${{ secrets.CDP_URL }}

        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

        REDIS_URL: ${{ secrets.REDIS_URL }}

        BENCH_LOOKUP: default
        BENCH_COMMITS_TABLE: benchmarks_commits
        BENCH_SCORES_TABLE: benchmarks_scores
        BENCH_USE_CDP: true
        BENCH_MATRIX_AI: ${{ matrix.ai }}

        COMMIT: ${{ github.sha }}
        BRANCH: ${{ env.BRANCH }}

        FF_LOG: debug

      run: npm run bench
      continue-on-error: true
