name: Node.js CI

on:
  push:
    branches: [ 'master', 'dev' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm run build --if-present
    - name: Run benchmarks
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        BENCH_KV: redis
        REDIS_URL: ${{ secrets.REDIS_URL }}
        FF_LOG: debug
      run: npm run bench
