name: Tests

on:
  push:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        attempt: [1, 2, 3]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm run build --if-present
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        FF_LOG: warn
      run: npm test-fast
      continue-on-error: ${{ matrix.attempt != 3 }}

    - name: Skip further attempts if successful
      if: ${{ matrix.attempt != 1 && steps.test.outcome == 'success' }}
      run: exit 0
